/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    workers: WorkerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    'product-types': ProductType;
    ingredients: Ingredient;
    'ingredients-discoveries': IngredientsDiscovery;
    products: Product;
    'source-products': SourceProduct;
    'product-discoveries': ProductDiscovery;
    'product-crawls': ProductCrawl;
    'product-aggregations': ProductAggregation;
    'crawl-results': CrawlResult;
    'discovery-results': DiscoveryResult;
    events: Event;
    creators: Creator;
    channels: Channel;
    videos: Video;
    'video-snippets': VideoSnippet;
    'video-mentions': VideoMention;
    'video-discoveries': VideoDiscovery;
    'video-processings': VideoProcessing;
    workers: Worker;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'ingredients-discoveries': {
      events: 'events';
    };
    products: {
      videoSnippets: 'video-snippets';
      videoMentions: 'video-mentions';
      aggregations: 'product-aggregations';
    };
    'source-products': {
      discoveries: 'discovery-results';
      crawls: 'crawl-results';
    };
    'product-discoveries': {
      discoveredProducts: 'discovery-results';
      events: 'events';
    };
    'product-crawls': {
      crawledProducts: 'crawl-results';
      events: 'events';
    };
    'product-aggregations': {
      events: 'events';
    };
    creators: {
      channels: 'channels';
    };
    channels: {
      videos: 'videos';
    };
    videos: {
      videoSnippets: 'video-snippets';
    };
    'video-snippets': {
      videoMentions: 'video-mentions';
    };
    'video-discoveries': {
      events: 'events';
    };
    'video-processings': {
      events: 'events';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'product-types': ProductTypesSelect<false> | ProductTypesSelect<true>;
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    'ingredients-discoveries': IngredientsDiscoveriesSelect<false> | IngredientsDiscoveriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'source-products': SourceProductsSelect<false> | SourceProductsSelect<true>;
    'product-discoveries': ProductDiscoveriesSelect<false> | ProductDiscoveriesSelect<true>;
    'product-crawls': ProductCrawlsSelect<false> | ProductCrawlsSelect<true>;
    'product-aggregations': ProductAggregationsSelect<false> | ProductAggregationsSelect<true>;
    'crawl-results': CrawlResultsSelect<false> | CrawlResultsSelect<true>;
    'discovery-results': DiscoveryResultsSelect<false> | DiscoveryResultsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    creators: CreatorsSelect<false> | CreatorsSelect<true>;
    channels: ChannelsSelect<false> | ChannelsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'video-snippets': VideoSnippetsSelect<false> | VideoSnippetsSelect<true>;
    'video-mentions': VideoMentionsSelect<false> | VideoMentionsSelect<true>;
    'video-discoveries': VideoDiscoveriesSelect<false> | VideoDiscoveriesSelect<true>;
    'video-processings': VideoProcessingsSelect<false> | VideoProcessingsSelect<true>;
    workers: WorkersSelect<false> | WorkersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Worker & {
        collection: 'workers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface WorkerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types".
 */
export interface ProductType {
  id: number;
  name: string;
  nameDE: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  status?: ('pending' | 'crawled' | 'uncrawled') | null;
  description?: string | null;
  casNumber?: string | null;
  ecNumber?: string | null;
  /**
   * Substance ID from CosIng database
   */
  cosIngId?: string | null;
  chemicalDescription?: string | null;
  functions?:
    | {
        function?: string | null;
        id?: string | null;
      }[]
    | null;
  itemType?: ('ingredient' | 'substance') | null;
  restrictions?: string | null;
  /**
   * CosIng page URL
   */
  sourceUrl?: string | null;
  crawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients-discoveries".
 */
export interface IngredientsDiscovery {
  id: number;
  /**
   * URL that determines which driver to use (e.g., "https://ec.europa.eu/growth/tools-databases/cosing/")
   */
  sourceUrl: string;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  /**
   * Max pages per batch. Empty = unlimited.
   */
  pagesPerTick?: number | null;
  discovered?: number | null;
  created?: number | null;
  existing?: number | null;
  errors?: number | null;
  currentTerm?: string | null;
  currentPage?: number | null;
  totalPagesForTerm?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Remaining search terms to process
   */
  termQueue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'start' | 'success' | 'info' | 'warning' | 'error';
  level?: ('debug' | 'info' | 'warn' | 'error') | null;
  component?: ('worker' | 'server') | null;
  labels?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  message: string;
  job?:
    | ({
        relationTo: 'product-discoveries';
        value: number | ProductDiscovery;
      } | null)
    | ({
        relationTo: 'product-crawls';
        value: number | ProductCrawl;
      } | null)
    | ({
        relationTo: 'ingredients-discoveries';
        value: number | IngredientsDiscovery;
      } | null)
    | ({
        relationTo: 'product-aggregations';
        value: number | ProductAggregation;
      } | null)
    | ({
        relationTo: 'video-discoveries';
        value: number | VideoDiscovery;
      } | null)
    | ({
        relationTo: 'video-processings';
        value: number | VideoProcessing;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-discoveries".
 */
export interface ProductDiscovery {
  id: number;
  /**
   * Category or product URLs, one per line. Product URLs (e.g. dm.de/...-p1234.html) create source products directly.
   */
  sourceUrls: string;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  /**
   * Max pages per batch. Empty = unlimited.
   */
  itemsPerTick?: number | null;
  /**
   * Milliseconds between requests. Default: 2000.
   */
  delay?: number | null;
  /**
   * Keep browser visible (non-headless).
   */
  debug?: boolean | null;
  productUrls?: string | null;
  /**
   * Products found on the page
   */
  discovered?: number | null;
  /**
   * New products created
   */
  created?: number | null;
  /**
   * Products already in database
   */
  existing?: number | null;
  /**
   * Internal state for resumable discovery
   */
  progress?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startedAt?: string | null;
  completedAt?: string | null;
  discoveredProducts?: {
    docs?: (number | DiscoveryResult)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discovery-results".
 */
export interface DiscoveryResult {
  id: number;
  discovery: number | ProductDiscovery;
  sourceProduct: number | SourceProduct;
  /**
   * Error message if this URL failed during discovery
   */
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Products crawled from source stores
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-products".
 */
export interface SourceProduct {
  id: number;
  /**
   * Global Trade Item Number
   */
  gtin?: string | null;
  status?: ('uncrawled' | 'crawled') | null;
  /**
   * URL from which this product was crawled (normalized: no query params, no trailing slash)
   */
  sourceUrl?: string | null;
  source?: ('dm' | 'mueller' | 'rossmann') | null;
  /**
   * Source-specific article number (e.g., DM Artikelnummer)
   */
  sourceArticleNumber?: string | null;
  /**
   * Product brand name
   */
  brandName?: string | null;
  name?: string | null;
  /**
   * Category breadcrumb, e.g. "Pflege -> Körperpflege -> Handcreme"
   */
  categoryBreadcrumb?: string | null;
  /**
   * Average rating (0-5)
   */
  rating?: number | null;
  /**
   * Total number of reviews
   */
  ratingNum?: number | null;
  /**
   * Product amount (e.g., 3, 100, 250)
   */
  amount?: number | null;
  /**
   * Unit of measurement (e.g., ml, g, Stück)
   */
  amountUnit?: string | null;
  /**
   * Product labels (e.g., Neu, Limitiert, dm-Marke)
   */
  labels?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Full product description extracted from source page (markdown)
   */
  description?: string | null;
  images?:
    | {
        url: string;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        dimension: string;
        options?:
          | {
              label: string;
              value?: string | null;
              gtin?: string | null;
              isSelected?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Timestamped price entries from each crawl
   */
  priceHistory?:
    | {
        recordedAt: string;
        /**
         * Price in cents
         */
        amount?: number | null;
        currency?: string | null;
        perUnitAmount?: number | null;
        perUnitCurrency?: string | null;
        /**
         * Reference quantity (e.g., 100 for "per 100 ml")
         */
        perUnitQuantity?: number | null;
        /**
         * Unit of measurement (e.g., ml, g, l, kg)
         */
        unit?: string | null;
        /**
         * Price movement vs previous record
         */
        change?: ('drop' | 'stable' | 'increase') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw ingredients text as crawled from source, including footnotes and annotations. Parsed into individual ingredients during product aggregation.
   */
  ingredientsText?: string | null;
  discoveries?: {
    docs?: (number | DiscoveryResult)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  crawls?: {
    docs?: (number | CrawlResult)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crawl-results".
 */
export interface CrawlResult {
  id: number;
  crawl: number | ProductCrawl;
  sourceProduct: number | SourceProduct;
  /**
   * Error message if the crawl failed for this product
   */
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-crawls".
 */
export interface ProductCrawl {
  id: number;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  /**
   * Products to crawl per batch.
   */
  itemsPerTick?: number | null;
  /**
   * Keep browser visible (non-headless).
   */
  debug?: boolean | null;
  /**
   * "All in Database" processes existing source-products. The other options target specific products.
   */
  type: 'all' | 'selected_urls' | 'selected_gtins' | 'from_discovery';
  /**
   * Which store(s) to crawl products from.
   */
  source?: ('all' | 'dm' | 'rossmann' | 'mueller') | null;
  /**
   * One product URL per line. The store is detected automatically from the URL.
   */
  urls?: string | null;
  /**
   * One GTIN per line. All matching source-products across the selected store(s) will be crawled.
   */
  gtins?: string | null;
  /**
   * Crawl the product URLs found by this discovery. Covers all stores that the discovery found.
   */
  discovery?: (number | null) | ProductDiscovery;
  /**
   * "Only Uncrawled" skips products that were already crawled. "Re-crawl All" resets them and crawls again.
   */
  scope?: ('uncrawled_only' | 'recrawl') | null;
  /**
   * Only re-crawl products last crawled more than this long ago. Leave empty to re-crawl everything.
   */
  minCrawlAge?: number | null;
  minCrawlAgeUnit?: ('minutes' | 'hours' | 'days' | 'weeks') | null;
  /**
   * Total products to crawl
   */
  total?: number | null;
  /**
   * Products successfully crawled
   */
  crawled?: number | null;
  /**
   * Products that failed to crawl
   */
  errors?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  crawledProducts?: {
    docs?: (number | CrawlResult)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-aggregations".
 */
export interface ProductAggregation {
  id: number;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  /**
   * Full: runs LLM classification (description, product type, attributes, claims), brand matching, ingredient matching, and image selection. Partial: only updates score history and basic product data (name, sources) — no LLM calls, no image downloads.
   */
  scope: 'full' | 'partial';
  /**
   * Products to aggregate per batch.
   */
  itemsPerTick?: number | null;
  type: 'all' | 'selected_gtins';
  /**
   * GTINs to aggregate, one per line
   */
  gtins?: string | null;
  /**
   * Language for the generated product description.
   */
  language?: ('de' | 'en') | null;
  /**
   * Ordered list of sources to prefer when selecting a product image. First source with images wins. Default: ["dm", "rossmann", "mueller"]
   */
  imageSourcePriority?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Total products to aggregate
   */
  total?: number | null;
  /**
   * Products successfully aggregated
   */
  aggregated?: number | null;
  /**
   * Products that failed to aggregate
   */
  errors?: number | null;
  /**
   * Total LLM tokens spent on ingredient matching
   */
  tokensUsed?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Products created or updated by this aggregation
   */
  products?: (number | Product)[] | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  lastCheckedSourceId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name?: string | null;
  /**
   * Global Trade Item Number
   */
  gtin?: string | null;
  description?: string | null;
  brand?: (number | null) | Brand;
  productType?: (number | null) | ProductType;
  /**
   * Primary product image (aggregated from source products)
   */
  image?: (number | null) | Media;
  publishedAt?: string | null;
  /**
   * Product warnings extracted from descriptions (e.g. "Avoid contact with eyes")
   */
  warnings?: string | null;
  /**
   * Target skin type as stated in the product description
   */
  skinApplicability?: ('normal' | 'sensitive' | 'mixed' | 'oily' | 'dry') | null;
  /**
   * Minimum pH level (0–14)
   */
  phMin?: number | null;
  /**
   * Maximum pH level (0–14)
   */
  phMax?: number | null;
  /**
   * How to use the product, extracted from descriptions
   */
  usageInstructions?: string | null;
  /**
   * A 2D array: outer = repeating day cycle, inner = up to 3 time slots [morning, midday, evening]. Each slot is 1 (use) or 0 (skip). An empty inner array [] means skip that day entirely. Example: [[1,0,1]] = daily morning+evening. [[1,0,0],[]] = every other day morning only.
   */
  usageSchedule?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Product ingredients (aggregated from sources)
   */
  ingredients?:
    | {
        /**
         * Raw ingredient name as listed on the product
         */
        name: string;
        /**
         * Link to ingredient database entry, if matched
         */
        ingredient?: (number | null) | Ingredient;
        id?: string | null;
      }[]
    | null;
  /**
   * Ingredient-based attributes with evidence from source products
   */
  productAttributes?:
    | {
        attribute:
          | 'containsAllergens'
          | 'containsSimpleAlcohol'
          | 'containsGluten'
          | 'containsSilicones'
          | 'containsSulfates'
          | 'containsParabens'
          | 'containsPegs'
          | 'containsFragrance'
          | 'containsMineralOil';
        sourceProduct: number | SourceProduct;
        evidenceType: 'ingredient' | 'descriptionSnippet';
        snippet?: string | null;
        start?: number | null;
        end?: number | null;
        ingredientNames?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Marketing and safety claims with evidence from source products
   */
  productClaims?:
    | {
        claim:
          | 'vegan'
          | 'crueltyFree'
          | 'unsafeForPregnancy'
          | 'pregnancySafe'
          | 'waterProof'
          | 'microplasticFree'
          | 'allergenFree'
          | 'simpleAlcoholFree'
          | 'glutenFree'
          | 'siliconeFree'
          | 'sulfateFree'
          | 'parabenFree'
          | 'pegFree'
          | 'fragranceFree'
          | 'mineralOilFree';
        sourceProduct: number | SourceProduct;
        evidenceType: 'ingredient' | 'descriptionSnippet';
        snippet?: string | null;
        start?: number | null;
        end?: number | null;
        ingredientNames?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  videoSnippets?: {
    docs?: (number | VideoSnippet)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  videoMentions?: {
    docs?: (number | VideoMention)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Timestamped snapshots of store and creator scores, recorded during each aggregation run
   */
  scoreHistory?:
    | {
        recordedAt: string;
        storeScore?: number | null;
        creatorScore?: number | null;
        /**
         * Score movement vs previous record (>= 5% relative change)
         */
        change?: ('drop' | 'stable' | 'increase') | null;
        id?: string | null;
      }[]
    | null;
  aggregations?: {
    docs?: (number | ProductAggregation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * When data sources were last aggregated into name, brand, and description
   */
  lastAggregatedAt?: string | null;
  /**
   * Links to crawled source product data
   */
  sourceProducts?: (number | SourceProduct)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-snippets".
 */
export interface VideoSnippet {
  id: number;
  matchingType?: ('barcode' | 'visual') | null;
  /**
   * Start time in seconds
   */
  timestampStart?: number | null;
  /**
   * End time in seconds
   */
  timestampEnd?: number | null;
  video: number | Video;
  image?: (number | null) | Media;
  referencedProducts?: (number | Product)[] | null;
  videoMentions?: {
    docs?: (number | VideoMention)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * 5 seconds of spoken context before this snippet
   */
  preTranscript?: string | null;
  /**
   * Spoken words within this snippet time range
   */
  transcript?: string | null;
  /**
   * 3 seconds of spoken context after this snippet
   */
  postTranscript?: string | null;
  screenshots?:
    | {
        image: number | Media;
        /**
         * 64x64 grayscale thumbnail used for image hashing
         */
        thumbnail?: (number | null) | Media;
        /**
         * Perceptual hash of the thumbnail
         */
        hash?: string | null;
        /**
         * Hamming distance to assigned cluster representative hash
         */
        distance?: number | null;
        /**
         * Cluster ID — screenshots with similar visual content share a cluster
         */
        screenshotGroup?: number | null;
        /**
         * EAN-13/EAN-8 barcode detected in this screenshot
         */
        barcode?: string | null;
        /**
         * Whether this screenshot was selected as a cluster representative for product recognition
         */
        recognitionCandidate?: boolean | null;
        /**
         * 128x128 color thumbnail used for product classification
         */
        recognitionThumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  channel: number | Channel;
  title: string;
  image?: (number | null) | Media;
  publishedAt?: string | null;
  processingStatus?: ('unprocessed' | 'processed') | null;
  /**
   * Duration in seconds
   */
  duration?: number | null;
  viewCount?: number | null;
  likeCount?: number | null;
  externalUrl?: string | null;
  /**
   * Full corrected transcript of the video audio
   */
  transcript?: string | null;
  /**
   * Word-level timestamps from speech recognition: [{ word, start, end, confidence }]
   */
  transcriptWords?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  videoSnippets?: {
    docs?: (number | VideoSnippet)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels".
 */
export interface Channel {
  id: number;
  creator: number | Creator;
  image?: (number | null) | Media;
  platform: 'youtube' | 'instagram' | 'tiktok';
  externalUrl?: string | null;
  /**
   * Platform-canonical URL (e.g. /channel/UC... for YouTube). Used for deduplication.
   */
  canonicalUrl?: string | null;
  videos?: {
    docs?: (number | Video)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators".
 */
export interface Creator {
  id: number;
  name: string;
  image?: (number | null) | Media;
  channels?: {
    docs?: (number | Channel)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-mentions".
 */
export interface VideoMention {
  id: number;
  videoSnippet: number | VideoSnippet;
  product: number | Product;
  /**
   * Spoken quotes about this product extracted from the video snippet
   */
  quotes?:
    | {
        text: string;
        /**
         * Short key takeaways from the quote, true to original wording
         */
        summary?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        sentiment: 'positive' | 'neutral' | 'negative' | 'mixed';
        /**
         * Score from -1 (very negative) to 1 (very positive)
         */
        sentimentScore?: number | null;
        id?: string | null;
      }[]
    | null;
  overallSentiment?: ('positive' | 'neutral' | 'negative' | 'mixed') | null;
  /**
   * Aggregate score from -1 (very negative) to 1 (very positive)
   */
  overallSentimentScore?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-discoveries".
 */
export interface VideoDiscovery {
  id: number;
  /**
   * The channel URL to discover videos from (e.g. https://www.youtube.com/@xskincare)
   */
  channelUrl: string;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  /**
   * Max videos per batch. Empty = unlimited.
   */
  itemsPerTick?: number | null;
  /**
   * Videos found on the channel
   */
  discovered?: number | null;
  /**
   * New videos created
   */
  created?: number | null;
  /**
   * Videos already in database
   */
  existing?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-processings".
 */
export interface VideoProcessing {
  id: number;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  /**
   * Videos to process per batch.
   */
  itemsPerTick?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  type: 'all_unprocessed' | 'single_video' | 'selected_urls';
  /**
   * The video to process
   */
  video?: (number | null) | Video;
  /**
   * Video or channel URLs to process, one per line
   */
  urls?: string | null;
  /**
   * Scene change detection threshold (0-1). Lower = more sensitive, more segments.
   */
  sceneThreshold?: number | null;
  /**
   * Hamming distance threshold for screenshot clustering (1-64). Lower = stricter grouping, more clusters.
   */
  clusterThreshold?: number | null;
  /**
   * Enable speech-to-text transcription via Deepgram and sentiment analysis.
   */
  transcriptionEnabled?: boolean | null;
  /**
   * Language for speech recognition.
   */
  transcriptionLanguage?: ('de' | 'en' | 'fr' | 'es' | 'it') | null;
  /**
   * Deepgram model to use for speech recognition.
   */
  transcriptionModel?: ('nova-3' | 'nova-2' | 'enhanced' | 'base') | null;
  /**
   * Total videos to process
   */
  total?: number | null;
  /**
   * Videos successfully processed
   */
  processed?: number | null;
  /**
   * Videos that failed to process
   */
  errors?: number | null;
  /**
   * Total LLM tokens consumed across all steps
   */
  tokensUsed?: number | null;
  /**
   * Tokens used for visual product recognition
   */
  tokensRecognition?: number | null;
  /**
   * Tokens used for LLM transcript correction
   */
  tokensTranscriptCorrection?: number | null;
  /**
   * Tokens used for sentiment & quote extraction
   */
  tokensSentiment?: number | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workers".
 */
export interface Worker {
  id: number;
  name: string;
  capabilities: (
    | 'product-crawl'
    | 'product-discovery'
    | 'ingredients-discovery'
    | 'video-discovery'
    | 'video-processing'
    | 'product-aggregation'
  )[];
  status: 'active' | 'disabled';
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'product-types';
        value: number | ProductType;
      } | null)
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'ingredients-discoveries';
        value: number | IngredientsDiscovery;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'source-products';
        value: number | SourceProduct;
      } | null)
    | ({
        relationTo: 'product-discoveries';
        value: number | ProductDiscovery;
      } | null)
    | ({
        relationTo: 'product-crawls';
        value: number | ProductCrawl;
      } | null)
    | ({
        relationTo: 'product-aggregations';
        value: number | ProductAggregation;
      } | null)
    | ({
        relationTo: 'crawl-results';
        value: number | CrawlResult;
      } | null)
    | ({
        relationTo: 'discovery-results';
        value: number | DiscoveryResult;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'creators';
        value: number | Creator;
      } | null)
    | ({
        relationTo: 'channels';
        value: number | Channel;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'video-snippets';
        value: number | VideoSnippet;
      } | null)
    | ({
        relationTo: 'video-mentions';
        value: number | VideoMention;
      } | null)
    | ({
        relationTo: 'video-discoveries';
        value: number | VideoDiscovery;
      } | null)
    | ({
        relationTo: 'video-processings';
        value: number | VideoProcessing;
      } | null)
    | ({
        relationTo: 'workers';
        value: number | Worker;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'workers';
        value: number | Worker;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'workers';
        value: number | Worker;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types_select".
 */
export interface ProductTypesSelect<T extends boolean = true> {
  name?: T;
  nameDE?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  description?: T;
  casNumber?: T;
  ecNumber?: T;
  cosIngId?: T;
  chemicalDescription?: T;
  functions?:
    | T
    | {
        function?: T;
        id?: T;
      };
  itemType?: T;
  restrictions?: T;
  sourceUrl?: T;
  crawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients-discoveries_select".
 */
export interface IngredientsDiscoveriesSelect<T extends boolean = true> {
  sourceUrl?: T;
  status?: T;
  pagesPerTick?: T;
  discovered?: T;
  created?: T;
  existing?: T;
  errors?: T;
  currentTerm?: T;
  currentPage?: T;
  totalPagesForTerm?: T;
  startedAt?: T;
  completedAt?: T;
  termQueue?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  gtin?: T;
  description?: T;
  brand?: T;
  productType?: T;
  image?: T;
  publishedAt?: T;
  warnings?: T;
  skinApplicability?: T;
  phMin?: T;
  phMax?: T;
  usageInstructions?: T;
  usageSchedule?: T;
  ingredients?:
    | T
    | {
        name?: T;
        ingredient?: T;
        id?: T;
      };
  productAttributes?:
    | T
    | {
        attribute?: T;
        sourceProduct?: T;
        evidenceType?: T;
        snippet?: T;
        start?: T;
        end?: T;
        ingredientNames?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  productClaims?:
    | T
    | {
        claim?: T;
        sourceProduct?: T;
        evidenceType?: T;
        snippet?: T;
        start?: T;
        end?: T;
        ingredientNames?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  videoSnippets?: T;
  videoMentions?: T;
  scoreHistory?:
    | T
    | {
        recordedAt?: T;
        storeScore?: T;
        creatorScore?: T;
        change?: T;
        id?: T;
      };
  aggregations?: T;
  lastAggregatedAt?: T;
  sourceProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-products_select".
 */
export interface SourceProductsSelect<T extends boolean = true> {
  gtin?: T;
  status?: T;
  sourceUrl?: T;
  source?: T;
  sourceArticleNumber?: T;
  brandName?: T;
  name?: T;
  categoryBreadcrumb?: T;
  rating?: T;
  ratingNum?: T;
  amount?: T;
  amountUnit?: T;
  labels?:
    | T
    | {
        label?: T;
        id?: T;
      };
  description?: T;
  images?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        dimension?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              gtin?: T;
              isSelected?: T;
              id?: T;
            };
        id?: T;
      };
  priceHistory?:
    | T
    | {
        recordedAt?: T;
        amount?: T;
        currency?: T;
        perUnitAmount?: T;
        perUnitCurrency?: T;
        perUnitQuantity?: T;
        unit?: T;
        change?: T;
        id?: T;
      };
  ingredientsText?: T;
  discoveries?: T;
  crawls?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-discoveries_select".
 */
export interface ProductDiscoveriesSelect<T extends boolean = true> {
  sourceUrls?: T;
  status?: T;
  itemsPerTick?: T;
  delay?: T;
  debug?: T;
  productUrls?: T;
  discovered?: T;
  created?: T;
  existing?: T;
  progress?: T;
  startedAt?: T;
  completedAt?: T;
  discoveredProducts?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-crawls_select".
 */
export interface ProductCrawlsSelect<T extends boolean = true> {
  status?: T;
  itemsPerTick?: T;
  debug?: T;
  type?: T;
  source?: T;
  urls?: T;
  gtins?: T;
  discovery?: T;
  scope?: T;
  minCrawlAge?: T;
  minCrawlAgeUnit?: T;
  total?: T;
  crawled?: T;
  errors?: T;
  startedAt?: T;
  completedAt?: T;
  crawledProducts?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-aggregations_select".
 */
export interface ProductAggregationsSelect<T extends boolean = true> {
  status?: T;
  scope?: T;
  itemsPerTick?: T;
  type?: T;
  gtins?: T;
  language?: T;
  imageSourcePriority?: T;
  total?: T;
  aggregated?: T;
  errors?: T;
  tokensUsed?: T;
  startedAt?: T;
  completedAt?: T;
  products?: T;
  events?: T;
  lastCheckedSourceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crawl-results_select".
 */
export interface CrawlResultsSelect<T extends boolean = true> {
  crawl?: T;
  sourceProduct?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discovery-results_select".
 */
export interface DiscoveryResultsSelect<T extends boolean = true> {
  discovery?: T;
  sourceProduct?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  level?: T;
  component?: T;
  labels?:
    | T
    | {
        label?: T;
        id?: T;
      };
  message?: T;
  job?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators_select".
 */
export interface CreatorsSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  channels?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels_select".
 */
export interface ChannelsSelect<T extends boolean = true> {
  creator?: T;
  image?: T;
  platform?: T;
  externalUrl?: T;
  canonicalUrl?: T;
  videos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  channel?: T;
  title?: T;
  image?: T;
  publishedAt?: T;
  processingStatus?: T;
  duration?: T;
  viewCount?: T;
  likeCount?: T;
  externalUrl?: T;
  transcript?: T;
  transcriptWords?: T;
  videoSnippets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-snippets_select".
 */
export interface VideoSnippetsSelect<T extends boolean = true> {
  matchingType?: T;
  timestampStart?: T;
  timestampEnd?: T;
  video?: T;
  image?: T;
  referencedProducts?: T;
  videoMentions?: T;
  preTranscript?: T;
  transcript?: T;
  postTranscript?: T;
  screenshots?:
    | T
    | {
        image?: T;
        thumbnail?: T;
        hash?: T;
        distance?: T;
        screenshotGroup?: T;
        barcode?: T;
        recognitionCandidate?: T;
        recognitionThumbnail?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-mentions_select".
 */
export interface VideoMentionsSelect<T extends boolean = true> {
  videoSnippet?: T;
  product?: T;
  quotes?:
    | T
    | {
        text?: T;
        summary?: T;
        sentiment?: T;
        sentimentScore?: T;
        id?: T;
      };
  overallSentiment?: T;
  overallSentimentScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-discoveries_select".
 */
export interface VideoDiscoveriesSelect<T extends boolean = true> {
  channelUrl?: T;
  status?: T;
  itemsPerTick?: T;
  discovered?: T;
  created?: T;
  existing?: T;
  startedAt?: T;
  completedAt?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-processings_select".
 */
export interface VideoProcessingsSelect<T extends boolean = true> {
  status?: T;
  itemsPerTick?: T;
  startedAt?: T;
  completedAt?: T;
  type?: T;
  video?: T;
  urls?: T;
  sceneThreshold?: T;
  clusterThreshold?: T;
  transcriptionEnabled?: T;
  transcriptionLanguage?: T;
  transcriptionModel?: T;
  total?: T;
  processed?: T;
  errors?: T;
  tokensUsed?: T;
  tokensRecognition?: T;
  tokensTranscriptCorrection?: T;
  tokensSentiment?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workers_select".
 */
export interface WorkersSelect<T extends boolean = true> {
  name?: T;
  capabilities?: T;
  status?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}