/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'dm-products': DmProduct;
    'dm-crawls': DmCrawl;
    'dm-crawl-items': DmCrawlItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'dm-crawls': {
      items: 'dm-crawl-items';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'dm-products': DmProductsSelect<false> | DmProductsSelect<true>;
    'dm-crawls': DmCrawlsSelect<false> | DmCrawlsSelect<true>;
    'dm-crawl-items': DmCrawlItemsSelect<false> | DmCrawlItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Products crawled from dm.de
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dm-products".
 */
export interface DmProduct {
  id: number;
  /**
   * Global Trade Item Number
   */
  gtin?: string | null;
  /**
   * Product brand name
   */
  brandName?: string | null;
  name: string;
  /**
   * Product category (e.g., Make-up)
   */
  type?: string | null;
  /**
   * Product pricing information
   */
  pricing?: {
    /**
     * Price in smallest currency unit (cents)
     */
    amount?: number | null;
    /**
     * ISO 4217 currency code
     */
    currency?: string | null;
    /**
     * Base price per unit in cents
     */
    perUnitAmount?: number | null;
    perUnitCurrency?: string | null;
    /**
     * Unit of measurement (e.g., l, kg)
     */
    unit?: string | null;
  };
  /**
   * Average rating (0-5)
   */
  rating?: number | null;
  /**
   * Total number of reviews
   */
  ratingNum?: number | null;
  /**
   * Product labels (e.g., Neu, Limitiert, dm-Marke)
   */
  labels?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL from which this product was crawled
   */
  sourceUrl?: string | null;
  /**
   * When this product was last crawled
   */
  crawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * DM crawl sessions tracking discovery and crawl progress
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dm-crawls".
 */
export interface DmCrawl {
  id: number;
  /**
   * The dm.de category URL being crawled
   */
  sourceUrl: string;
  /**
   * Current status of the crawl
   */
  status?: ('pending' | 'discovering' | 'discovered' | 'crawling' | 'completed' | 'failed') | null;
  /**
   * Total number of products reported by dm.de
   */
  totalCount?: number | null;
  /**
   * Number of items discovered during discovery phase
   */
  itemsDiscovered?: number | null;
  /**
   * Number of items successfully crawled
   */
  itemsCrawled?: number | null;
  /**
   * Error message if crawl failed
   */
  error?: string | null;
  discoveredAt?: string | null;
  completedAt?: string | null;
  items?: {
    docs?: (number | DmCrawlItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dm-crawl-items".
 */
export interface DmCrawlItem {
  id: number;
  crawl: number | DmCrawl;
  gtin: string;
  productUrl?: string | null;
  status?: ('pending' | 'crawled' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'dm-products';
        value: number | DmProduct;
      } | null)
    | ({
        relationTo: 'dm-crawls';
        value: number | DmCrawl;
      } | null)
    | ({
        relationTo: 'dm-crawl-items';
        value: number | DmCrawlItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dm-products_select".
 */
export interface DmProductsSelect<T extends boolean = true> {
  gtin?: T;
  brandName?: T;
  name?: T;
  type?: T;
  pricing?:
    | T
    | {
        amount?: T;
        currency?: T;
        perUnitAmount?: T;
        perUnitCurrency?: T;
        unit?: T;
      };
  rating?: T;
  ratingNum?: T;
  labels?:
    | T
    | {
        label?: T;
        id?: T;
      };
  sourceUrl?: T;
  crawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dm-crawls_select".
 */
export interface DmCrawlsSelect<T extends boolean = true> {
  sourceUrl?: T;
  status?: T;
  totalCount?: T;
  itemsDiscovered?: T;
  itemsCrawled?: T;
  error?: T;
  discoveredAt?: T;
  completedAt?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dm-crawl-items_select".
 */
export interface DmCrawlItemsSelect<T extends boolean = true> {
  crawl?: T;
  gtin?: T;
  productUrl?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}