/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    categories: Category;
    ingredients: Ingredient;
    'ingredients-discoveries': IngredientsDiscovery;
    products: Product;
    'dm-products': DmProduct;
    'source-discoveries': SourceDiscovery;
    'source-crawls': SourceCrawl;
    'product-aggregations': ProductAggregation;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'ingredients-discoveries': {
      events: 'events';
    };
    'source-discoveries': {
      events: 'events';
    };
    'source-crawls': {
      events: 'events';
    };
    'product-aggregations': {
      events: 'events';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    'ingredients-discoveries': IngredientsDiscoveriesSelect<false> | IngredientsDiscoveriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'dm-products': DmProductsSelect<false> | DmProductsSelect<true>;
    'source-discoveries': SourceDiscoveriesSelect<false> | SourceDiscoveriesSelect<true>;
    'source-crawls': SourceCrawlsSelect<false> | SourceCrawlsSelect<true>;
    'product-aggregations': ProductAggregationsSelect<false> | ProductAggregationsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Select a parent category to create a subcategory
   */
  parent?: (number | null) | Category;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  status?: ('pending' | 'crawled' | 'crawl_failed' | 'crawl_not_found') | null;
  description?: string | null;
  casNumber?: string | null;
  ecNumber?: string | null;
  /**
   * Substance ID from CosIng database
   */
  cosIngId?: string | null;
  chemicalDescription?: string | null;
  functions?:
    | {
        function?: string | null;
        id?: string | null;
      }[]
    | null;
  itemType?: ('ingredient' | 'substance') | null;
  restrictions?: string | null;
  /**
   * CosIng page URL
   */
  sourceUrl?: string | null;
  crawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients-discoveries".
 */
export interface IngredientsDiscovery {
  id: number;
  /**
   * URL that determines which driver to use (e.g., "https://ec.europa.eu/growth/tools-databases/cosing/")
   */
  sourceUrl: string;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  discovered?: number | null;
  created?: number | null;
  existing?: number | null;
  errors?: number | null;
  currentTerm?: string | null;
  currentPage?: number | null;
  totalPagesForTerm?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Remaining search terms to process
   */
  termQueue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'error' | 'warning' | 'info';
  message: string;
  job?:
    | ({
        relationTo: 'source-discoveries';
        value: number | SourceDiscovery;
      } | null)
    | ({
        relationTo: 'source-crawls';
        value: number | SourceCrawl;
      } | null)
    | ({
        relationTo: 'ingredients-discoveries';
        value: number | IngredientsDiscovery;
      } | null)
    | ({
        relationTo: 'product-aggregations';
        value: number | ProductAggregation;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-discoveries".
 */
export interface SourceDiscovery {
  id: number;
  /**
   * The category URL to discover products from
   */
  sourceUrl: string;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  /**
   * Products found on the page
   */
  discovered?: number | null;
  /**
   * New products created
   */
  created?: number | null;
  /**
   * Products already in database
   */
  existing?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-crawls".
 */
export interface SourceCrawl {
  id: number;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  source: 'all' | 'dm';
  type: 'all' | 'selected_gtins';
  /**
   * List of GTINs to crawl
   */
  gtins?:
    | {
        gtin: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Products successfully crawled
   */
  crawled?: number | null;
  /**
   * Products that failed to crawl
   */
  errors?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-aggregations".
 */
export interface ProductAggregation {
  id: number;
  status?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  type: 'all' | 'selected_gtins';
  /**
   * List of GTINs to aggregate
   */
  gtins?:
    | {
        gtin: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Products successfully aggregated
   */
  aggregated?: number | null;
  /**
   * Products that failed to aggregate
   */
  errors?: number | null;
  /**
   * Total LLM tokens spent on ingredient matching
   */
  tokensUsed?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  lastCheckedSourceId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name?: string | null;
  /**
   * Global Trade Item Number
   */
  gtin?: string | null;
  description?: string | null;
  brand?: (number | null) | Brand;
  category?: (number | null) | Category;
  publishedAt?: string | null;
  /**
   * Product ingredients (aggregated from sources)
   */
  ingredients?: (number | Ingredient)[] | null;
  /**
   * When data sources were last aggregated into name, category, and description
   */
  lastAggregatedAt?: string | null;
  aggregationStatus?:
    | (
        | 'pending'
        | 'success'
        | 'brand_matching_error'
        | 'category_matching_error'
        | 'ingredient_matching_error'
        | 'failed'
      )
    | null;
  aggregationErrors?: string | null;
  /**
   * Link to crawled DM product data
   */
  dmProduct?: (number | null) | DmProduct;
  updatedAt: string;
  createdAt: string;
}
/**
 * Products crawled from dm.de
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dm-products".
 */
export interface DmProduct {
  id: number;
  status?: ('uncrawled' | 'crawled' | 'failed') | null;
  /**
   * Global Trade Item Number
   */
  gtin?: string | null;
  /**
   * Product brand name
   */
  brandName?: string | null;
  name?: string | null;
  /**
   * Product category (e.g., Make-up)
   */
  type?: string | null;
  /**
   * Average rating (0-5)
   */
  rating?: number | null;
  /**
   * Total number of reviews
   */
  ratingNum?: number | null;
  /**
   * Product labels (e.g., Neu, Limitiert, dm-Marke)
   */
  labels?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Product pricing information
   */
  pricing?: {
    /**
     * Price in smallest currency unit (cents)
     */
    amount?: number | null;
    /**
     * ISO 4217 currency code
     */
    currency?: string | null;
    /**
     * Base price per unit in cents
     */
    perUnitAmount?: number | null;
    perUnitCurrency?: string | null;
    /**
     * Unit of measurement (e.g., l, kg)
     */
    unit?: string | null;
  };
  /**
   * Raw ingredient strings as crawled from dm.de
   */
  ingredients?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL from which this product was crawled
   */
  sourceUrl?: string | null;
  /**
   * When this product was last crawled
   */
  crawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'ingredients-discoveries';
        value: number | IngredientsDiscovery;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'dm-products';
        value: number | DmProduct;
      } | null)
    | ({
        relationTo: 'source-discoveries';
        value: number | SourceDiscovery;
      } | null)
    | ({
        relationTo: 'source-crawls';
        value: number | SourceCrawl;
      } | null)
    | ({
        relationTo: 'product-aggregations';
        value: number | ProductAggregation;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  description?: T;
  casNumber?: T;
  ecNumber?: T;
  cosIngId?: T;
  chemicalDescription?: T;
  functions?:
    | T
    | {
        function?: T;
        id?: T;
      };
  itemType?: T;
  restrictions?: T;
  sourceUrl?: T;
  crawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients-discoveries_select".
 */
export interface IngredientsDiscoveriesSelect<T extends boolean = true> {
  sourceUrl?: T;
  status?: T;
  discovered?: T;
  created?: T;
  existing?: T;
  errors?: T;
  currentTerm?: T;
  currentPage?: T;
  totalPagesForTerm?: T;
  startedAt?: T;
  completedAt?: T;
  termQueue?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  gtin?: T;
  description?: T;
  brand?: T;
  category?: T;
  publishedAt?: T;
  ingredients?: T;
  lastAggregatedAt?: T;
  aggregationStatus?: T;
  aggregationErrors?: T;
  dmProduct?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dm-products_select".
 */
export interface DmProductsSelect<T extends boolean = true> {
  status?: T;
  gtin?: T;
  brandName?: T;
  name?: T;
  type?: T;
  rating?: T;
  ratingNum?: T;
  labels?:
    | T
    | {
        label?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        amount?: T;
        currency?: T;
        perUnitAmount?: T;
        perUnitCurrency?: T;
        unit?: T;
      };
  ingredients?:
    | T
    | {
        name?: T;
        id?: T;
      };
  sourceUrl?: T;
  crawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-discoveries_select".
 */
export interface SourceDiscoveriesSelect<T extends boolean = true> {
  sourceUrl?: T;
  status?: T;
  discovered?: T;
  created?: T;
  existing?: T;
  startedAt?: T;
  completedAt?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-crawls_select".
 */
export interface SourceCrawlsSelect<T extends boolean = true> {
  status?: T;
  source?: T;
  type?: T;
  gtins?:
    | T
    | {
        gtin?: T;
        id?: T;
      };
  crawled?: T;
  errors?: T;
  startedAt?: T;
  completedAt?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-aggregations_select".
 */
export interface ProductAggregationsSelect<T extends boolean = true> {
  status?: T;
  type?: T;
  gtins?:
    | T
    | {
        gtin?: T;
        id?: T;
      };
  aggregated?: T;
  errors?: T;
  tokensUsed?: T;
  startedAt?: T;
  completedAt?: T;
  events?: T;
  lastCheckedSourceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  message?: T;
  job?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}